---
- hosts: workstation

  tasks:
    - name: Install docker toolbox
      homebrew_cask: name=dockertoolbox state=present
      notify:
        - configure docker toolbox
      sudo: false

  handlers:
    - name: configure docker toolbox
      shell: docker-machine create --driver virtualbox default
      sudo: false
