---
- hosts: workstation

  tasks:
    - name: Installs atom plugins
      shell: apm install {{ item }} creates="~/.atom/packages/{{item}}"
      with_items:
        - go-plus
        - go-rename
        - project-manager
        - file-icons
        - advanced-open-file
        - slime
        - dash
        - atom-jinja2
        - language-ansible
        - language-docker
        - language-latex
        - language-pfm
        - langage-terraform
        - latex-plus
        - linter-docker
        - markdown-delux
        - markdown-preview-plus
        - pdf-view
        - pigments
      sudo: false
