---
cache_dir: ~/Library/Caches/battleschool

sources:
  local:
    - homebrew.yml
    - karabiner.yml
    - lastpass.yml
    - docker-toolbox.yml
    - sonos.yml

  git:
    - name: 'osx'
      repo: 'https://github.com/spencergibb/ansible-osx'
      playbooks:
         - atom.yml
         - chrome-stable.yml
         - dropbox.yml
         - iterm2.yml
         - java8.yml
         - spectacle.yml
         - seil.yml
         - skype.yml
