---
- hosts: workstation

  tasks:
    - name: Prepare go source directories
      file: state=directory path=~/gocode/src/github.com/pellegrino
      sudo: false

    - name: Install hg
      homebrew: name=hg state=present
      sudo: false

    - name: Install golang
      homebrew: name=go state=present
      sudo: false

    - name: Install go vet
      shell: go get golang.org/x/tools/cmd/vet creates=gocode/src/golang.org/x/tools/cmd/vet/
      sudo: false

    - name: Install godoc
      shell: go get golang.org/x/tools/cmd/godoc creates=gocode/src/golang.org/x/tools/cmd/godoc/
      sudo: false
