---
- hosts: workstation

  tasks:
    - name: install homebrew
      sudo: false
      mac_pkg: pkg_type=script script_creates=/usr/local/bin/brew
               script_data='\n' script_exe=/usr/bin/ruby
               url=https://raw.githubusercontent.com/Homebrew/install/master/install

    - name: Install cask
      homebrew_tap: tap=caskroom/cask state=present
      sudo: false

    - name: Install cask completions
      homebrew_tap: tap=homebrew/completions state=present
      sudo: false
