---
- hosts: workstation

  tasks:
    - name: install homebrew
      sudo: false
      mac_pkg: pkg_type=script script_creates=/usr/local/bin/brew
               script_data='\n' script_exe=/usr/bin/ruby
               url=https://raw.githubusercontent.com/Homebrew/install/master/install

    - name: Install cask
      homebrew: name=caskroom/cask/brew-cask state=present
      sudo: false

    - name: Install cask completions
      homebrew: name=homebrew/completions/brew-cask-completion state=present
      sudo: false
