---
- hosts: workstation

  tasks:
    - name: Download atom debian package
      get_url: url=https://github.com/atom/atom/releases/download/v1.3.0/atom-amd64.deb dest=target/atom-amd64.deb

    - name: Installs atom using the debian package
      apt: deb=target/atom-amd64.deb

    - name: Installs atom plugins
      shell: apm install {{ item }} creates="~/.atom/packages/{{item}}"
      with_items:
        - go-plus
        - go-rename
        - project-manager
        - file-icons
        - advanced-open-file
      sudo: false
