---
- hosts: workstation

  tasks:
    - name: Upgrades packages
      apt: upgrade=yes update_cache=yes

    - name: Installs extra packages
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - ubuntu-restricted-extras
        - ttf-mscorefonts-installer
        - transmission
        - tree
        - ack-grep
        - aptitude
        - nodejs
        - npm
        - nodejs-legacy
