---
- hosts: workstation

  tasks:
    - name: Download dropbox debian package
      get_url: url=https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb dest=target/dropbox.deb

    - name: Installs dropbox using the debian package
      apt: deb=target/dropbox.deb
