---
- hosts: workstation
  tasks:
    - name: Swap Cmd and Alt keys on apple keyboards
      lineinfile: dest=/etc/modprobe.d/hid_apple.conf create=yes state=present line="options hid_apple swap_opt_cmd=1"
      notify: update initramfs

  handlers:
    - name: update initramfs
      command: update-initramfs -u -k all
