---
- hosts: workstation

  tasks:
    - name: Download slack debian package
      get_url: url=https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-desktop-1.2.6-amd64.deb dest=target/slack.deb

    - name: Installs slack using the debian package
      apt: deb=target/slack.deb
