---
cache_dir: ~/.battleschool

sources:
  local:
    - atom.yml
    - slack.yml
#    - homebrew.yml
#    - git.yml
#    - bash.yml
#    - golang.yml
#    - hyper-key.yml
#    - lastpass.yml
#    - docker-toolbox.yml
#    - sonos.yml
#    - slate.yml
#    - vpn.yml
#    - intellij-idea-ce.yml
#    - transmission.yml
#    - slack.yml
#    - flux.yml
